plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xuvenz.portraitforcer'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xuvenz.portraitforcer'
        minSdk 23
        targetSdk 28
        versionCode 4
        versionName '1.2'
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
